from typing import Iterable, Iterator, Sequence

import numpy as np

Card = np.int8
CardColor = np.int8
Player = np.int8
GameResult = np.int8
FormationType = np.int8
Move = np.int16

NUM_COLORS: int
NUM_RANKS: int
NUM_CARDS: int
NUM_FLAGS: int
FORMATION_SIZE: int
HAND_SIZE: int
MAX_LEGAL_MOVES: int

RED: CardColor
YELLOW: CardColor
BLUE: CardColor
GREEN: CardColor
PURPLE: CardColor
ORANGE: CardColor
NULL_COLOR: CardColor

NULL_CARD: Card

FIRST: Player
SECOND: Player
NULL_PLAYER: Player

FIRST_WIN: GameResult
SECOND_WIN: GameResult
DRAW: GameResult
NOT_OVER: GameResult

HOST: FormationType
SKIRMISHER: FormationType
BATTALION: FormationType
PHALANX: FormationType
WEDGE: FormationType
NULL_FORMATION: FormationType

PASS_MOVE: Move
NULL_MOVE: Move

NULL_STRENGTH: int

ALL_CARDS: np.uint64
ALL_FLAGS: int

def to_opponent(player: Player) -> Player: ...
def player_to_str(player: Player) -> str: ...
def result_to_str(result: GameResult) -> str: ...
def formation_type_to_str(formation: FormationType) -> str: ...

def make_card(color: CardColor, rank: int) -> Card: ...
def card_color(card: Card) -> CardColor: ...
def card_rank(card: Card) -> int: ...
def card_to_str(card: Card) -> str: ...
def parse_card_str(s: str) -> Card: ...

def make_move(card: Card, flag: int) -> Move: ...
def move_card(move: Move) -> Card: ...
def move_flag(move: Move) -> int: ...
def move_to_str(move: Move) -> str: ...
def parse_move_str(s: str) -> Move: ...

def evaluate_formation(a: Card, b: Card, c: Card) -> int: ...
def formation_type(a: Card, b: Card, c: Card) -> FormationType: ...
def strength_to_formation_type(strength: int) -> FormationType: ...
def strength_to_sum(strength: int) -> int: ...
def best_completion(partial: Iterable[Card], available: np.uint64 | int) -> int: ...
def worst_completion(partial: Iterable[Card], available: np.uint64 | int) -> int: ...

def judge_flag(first_cards: Iterable[Card], second_cards: Iterable[Card], board: np.uint64 | int,
               turn_player: Player, first_completer: Player | None = None) -> Player: ...

class CardIterator(Iterator[Card]):
    def __init__(self, bits: np.uint64 | int) -> None: ...
    def __iter__(self) -> CardIterator: ...
    def __next__(self) -> Card: ...
    def __len__(self) -> int: ...

class GameState:
    def __init__(self, seed: int | None = None) -> None: ...
    def reset(self, seed: int | None = None) -> None: ...
    def set_position(self, side_to_move: Player,
                     hands: tuple[Iterable[Card], Iterable[Card]],
                     flags: Sequence[tuple[Iterable[Card], Iterable[Card]]],
                     deck: Iterable[Card] = (),
                     owners: Sequence[Player | None] | None = None,
                     first_completers: Sequence[Player | None] | None = None,
                     first_player: Player | None = None) -> None: ...

    @property
    def side_to_move(self) -> Player: ...
    @property
    def first_player(self) -> Player: ...
    @property
    def result(self) -> GameResult: ...
    @property
    def winner(self) -> Player: ...
    @property
    def is_terminal(self) -> bool: ...
    @property
    def is_forced_termination(self) -> bool: ...
    @property
    def consecutive_pass_count(self) -> int: ...
    @property
    def move_count(self) -> int: ...
    @property
    def deck_count(self) -> int: ...
    @property
    def board_cards(self) -> np.uint64: ...

    def get_hand(self, player: Player) -> np.uint64: ...
    def get_hand_count(self, player: Player) -> int: ...
    def get_unseen_cards(self, player: Player) -> np.uint64: ...
    def get_claimed_flags(self, player: Player) -> int: ...
    def get_placeable_flags(self, player: Player) -> int: ...
    def get_flag_owner(self, flag: int) -> Player: ...
    def get_flag_first_completer(self, flag: int) -> Player: ...
    def get_flag_cards(self, flag: int, player: Player) -> list[Card]: ...
    def get_flag_strength(self, flag: int, player: Player) -> int: ...

    def get_legal_moves(self) -> np.ndarray: ...
    def is_legal(self, move: Move) -> bool: ...
    def play(self, move: Move) -> int: ...
    def undo(self) -> None: ...
    def determinize(self, player: Player, seed: int | None = None) -> None: ...
    def random_playout(self, seed: int | None = None) -> GameResult: ...

    def copy_to(self, dest: GameState) -> None: ...
    def copy(self) -> GameState: ...
